### PR TITLE
Add workflow to publish package to pypi

### PR DESCRIPTION
**Pull request by marmig0404**
This PR would enable a workflow to publish this package to PyPI on a push.
I've already published the current version for use as a dependency for [my project](https://github.com/marmig0404/stl-in-mc).

@cpederkoff I can transfer ownership of this package on PyPI to you, make an account [here](https://pypi.org/).
After, set a Github secret **"PYPI_API_TOKEN"** as your PyPI API token to enable the workflow.

### CODE REVIEW

**Comment by marmig0404** [comment]
Noticing [your comment](https://github.com/cpederkoff/stl-to-voxel/pull/32#pullrequestreview-662339196), I can take down the PyPI package if you still stand by this.

**Comment by cpederkoff** [comment]
Hi @marmig0404, thanks for doing this work! It's much appreciated! Would you mind transferring the PyPI package to https://pypi.org/user/cpederkoff/ ?
After that I can set the github secret, approve this change and merge.

**Comment by marmig0404** [comment]
> Would you mind transferring the PyPI package to https://pypi.org/user/cpederkoff/ ?


Done! I'll change my role on pypi to maintainer once you accept.

**Comment by marmig0404** [comment]
Pypi won't let me demote myself to maintainer, I'll have to investigate further...

**Comment by cpederkoff** [comment]
No worries, I just did it

**Pull request merged**
