### PR TITLE
mesh triangle check edits to slice.py

### PR DESCRIPTION
**Pull request by silverscorpio**
With respect to this discussion - https://github.com/cpederkoff/stl-to-voxel/commit/81df3e656f7cfc7fec6c28aef030e661dedade05#commitcomment-50249160

1. In slice.py, check for correct mesh triangle points has been added from previous working commit
2. Edited doExport function in stltovoxel.py file in accordance to the first point

Hope it helps.

Thanks.

### CODE REVIEW

**Comment by youngkiu** [comment]
@cpederkoff 
What if the commit: 0faf8394b2e5f93255863563a664f1a3cd367ff5 had been based on PR https://github.com/cpederkoff/stl-to-voxel/pull/18?

**Comment by silverscorpio** [comment]
@youngkiu I just got the email for the commit (0faf8394b2e5f93255863563a664f1a3cd367ff5) @cpederkoff did. Saw this commit now- his commit seems better as it in line with the three changes he had done earlier on 25.04.2021 to speed up the code (380db5bc4a740ee31479009b129fc7407b14816c, 81df3e656f7cfc7fec6c28aef030e661dedade05, 0cf2f598acf17db4773b0d1adcadfe6e70249004). Keeps the code short and clean, I guess. Both codes work - kinda two versions haha!

I guess, I could maybe close this PR now since the issue has been addressed and resolved?

**Comment by youngkiu** [comment]
@silverscorpio 
I asked a question because even if the commit: 0faf839 code comes in completely, it looks better to be merged after working based on PR #18 in git revision history.

**Comment by silverscorpio** [comment]
@youngkiu , Right! Get your point, yes, could be done, seems legit!

**Comment by cpederkoff** [comment]
Closing for now. Thanks for contributing @silverscorpio . Sorry to take a different path to fix the bug. I'm looking forward to your pull requests in the future. :)

**Comment by silverscorpio** [comment]
@cpederkoff Cool bro! No issues, the problem was discovered and resolved for future users of the code, that's the main thing! All good! Thanks.

**Pull request closed without merging**
