### PR TITLE
Fix the bug of Issues/16 

### PR DESCRIPTION
**Pull request by youngkiu**
There was a bug in some code in https://github.com/cpederkoff/stl-to-voxel/pull/12, https://github.com/cpederkoff/stl-to-voxel/pull/12/commits/b948ef8e942f8f60729b693a259c860609fcaa9e

I rolled back the bug commit, and added the [Stanford_Bunny.stl](https://commons.wikimedia.org/wiki/File:Stanford_Bunny.stl) file as an example stl file.
[rand.stl](https://file.io/FqsVtgs5MgHx) uploaded from https://github.com/cpederkoff/stl-to-voxel/issues/16#issuecomment-821758637  has also been verified as working.

@silverscorpio, Thank you

### CODE REVIEW

**Comment by silverscorpio** [comment]
Great, it was discovered by you & fixed! @youngkiu Thanks to you m8! :)

**Comment by youngkiu** [comment]
I got to know by https://github.com/cpederkoff/stl-to-voxel/issues/16.

@cpederkoff
Please review and merge.

**Review by cpederkoff — APPROVED** [review]
Looks great. Thanks @youngkiu

**Comment by silverscorpio** [comment]
@cpederkoff Thank you.

**Pull request merged**
